"""Add unique constraint on spotprice table

Revision ID: d8beaed6a56e
Revises: 9f988116d214
Create Date: 2025-02-04 01:10:26.443416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8beaed6a56e'
down_revision: Union[str, None] = '9f988116d214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lastupdate', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint('symbol_timestamp_uc', 'spotprice', ['symbol', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('symbol_timestamp_uc', 'spotprice', type_='unique')
    op.alter_column('lastupdate', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
